### ISSUE TITLE
translatorTrait

### ISSUE THREAD

**Issue by michaltupy** [nattreid/mailchimp#1]
Tuto chybu nevim jak opravit, predpokaldam ze vyuziva nektere z dalsich rozsireni ale jake? Mohl bych poprosit o doplneni do napovedy jestlize neni v zavislostech dekuji.

DIky

**Comment by attreid** [comment]
Díky za report.
Trait nadále není nutný, takže by to mělo jet.

**Comment by jetpack3331** [comment]
@attreid No nicmene kdyz jej nainstaluju pres
composer require nattreid/mailchimp

Porad mam tu chybu s traitem:

`Trait 'NAttreid\Cms\ExtensionTranslatorTrait' not found`

**Comment by attreid** [comment]
Teď jsem to zkoušel v čistém nette sandboxu a Trait to po mě nechtělo.
Je tam podmínka, která kontroluje zda trait použít
https://github.com/nattreid/mailchimp/blob/d1e473e09969534ebcb70b65225176782eafd769/src/DI/MailChimpExtension.php#L14

**Comment by jetpack3331** [comment]
Divne. Ja si ciste nainstaloval nette pres composer a pridal jsem tvoji knihovnu pres 
`composer require nattreid/mailchimp`

Je na composeru aktualni kod?

**Comment by attreid** [comment]
možná ještě tohle, nette sandbox má v composer.json php verzi 5.6, takze to stáhne mailchimp 1.0.5, kde chyba není opravena. Nověější verze už chtějí php 7.1, takže upravit podmínky pro sandbox na php 7.1 a už to bude ok

**Comment by jetpack3331** [comment]
No ja mam prave na localu php:
PHP 7.1.13 (cli) (built: Jan  3 2018 20:16:04) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

**Comment by attreid** [comment]
To jo, ale je důležité jak je nastavený composer.json v sandboxu. Jestli tam je verze php 5.6 stáhne to verzi mailchimpu, které ji podporuje. A v té není tato chyba opravena

**Comment by jetpack3331** [comment]
Pouzivam:
Composer version 1.7.3 2018-11-01 10:05:06
